### ISSUE TITLE
acsone/bobtemplate

### ISSUE THREAD

**Issue by rvalyi** [akretion/voodoo-image#13]
I suggest to add this module in the image for dev convenience:
https://github.com/acsone/bobtemplates.odoo
so something like:
sudo pip install git+https://github.com/acsone/bobtemplates.odoo.git

**Comment by bealdav** [comment]
I saw this module too, nice

But you use it inside docker or outside ?

**Comment by rvalyi** [comment]
@bealdav it's easy to run it outside too. Not sure if packaging it inside is handy or not...
Anyway duplicate of https://github.com/akretion/voodoo/issues/45
